config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  namespace :owner do
    resources :dashboard, only: [:index]
    resources :properties, only: [:new, :create, :show, :destroy]
    resources :houses, only: [:destroy]
  end
  
  namespace :tenant do
    resources :dashboard, only: [:index]
  end
  
  namespace :admin do
    resources :dashboard, only: [:index]
  end
  

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :property
  belongs_to :tenant, class_name: 'User', foreign_key: 'tenant_id'
  validates :name, presence: true
  validates :description, presence: true
  validates :image_url, presence:true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :houses
  validates :name, presence: true
  validates :image_url, presence: true
  validates :location_name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  belongs_to :tenant, class_name: 'User', foreign_key: 'tenant_id'
  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :properties, class_name: 'Property', foreign_key: 'owner_id'
  has_many :houses, class_name: 'House', foreign_key: 'house_id'
  has_many :requests, class_name: 'Request', foreign_key: 'owner_id'
  has_many :requests, class_name: 'Request', foreign_key: 'tenant_id'
  validates :name, presence: true
  validates :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    before_action :update_allowed_parameters, if: :devise_controller?
  
    protected
  
    def update_allowed_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :telephone, :email, :password, :role) }
      devise_parameter_sanitizer.permit(:account_update) do |u|
        u.permit(:name, :telephone, :email, :password, :current_password, :role)
      end
    end
  
    def after_sign_in_path_for(resource)
      if resource.role.present?
        case resource.role.downcase
        when 'owner'
          owner_dashboard_index_path
        when 'tenant'
          owner_dashboard_index_path
        when 'admin'
          admin_dashboard_index_path
        else
          super
        end
      else
        super
      end
    end

    def after_sign_out_path_for(resource_or_scope)
      root_path
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @vacant_houses = House.where(occupied: false)
  end
end

app/controllers/owner/dashboard_controller.rb
class Owner::DashboardController < ApplicationController
    before_action :authenticate_user! # Ensure user is authenticated
  
    def index
      @properties = current_user.properties
      @user=current_user
    end

    def predict_rent
        openai_client = OpenAI::Client.new(
            api_key: ENV['OPENAI_API_KEY'],
        )

        rental_listing = {
            bedrooms: 2,
            neighborhood: 'Nyarugenge',
            condition: 'good',
            furnishings: 'furnished',
        }

        rental_listing_json = rental_listing.to_json

        response = openai_client.completions(
            prompt: "What is the estimated rent for a two-bedroom house in Nyarugenge, Kigali, Rwanda with the following characteristics: #{rental_listing_json}",
            max_tokens: 64,
            temperature: 0.9,
            top_p: 0.9,
        )

        predicted_rent = response.choices[0].text.split(' ')[-1]
        predicted_rent = '%.2f' % predicted_rent
        return predicted_rent
    end




  
    private
  
    # Calculate total rent collected for the current month for a specific property
    def calculate_current_month_rent(property)
      property.houses.where(paid: true).sum(:price)
    end
  
    # Calculate the percentage of rent collected for a specific property
    def calculate_percentage_collected(property)
      total_rent = property.houses.sum(:price)
      return 0 if total_rent.zero?
  
      collected_rent = property.houses.where(paid: true).sum(:price)
      (collected_rent / total_rent.to_f) * 100
    end
  
    helper_method :calculate_current_month_rent, :calculate_percentage_collected
  end
  

app/controllers/owner/houses_controller.rb
class Owner::HousesController < ApplicationController
    before_action :authenticate_user
  
    def destroy
      @house = House.find(params[:id])
      @house.destroy
      redirect_to property_path(@house.property), notice: 'House was successfully deleted.'
    end
  end
  

app/controllers/owner/properties_controller.rb
class Owner::PropertiesController < ApplicationController
    before_action :authenticate_user! # Ensure user is authenticated
  
    def new
      @property = Property.new
      @user=current_user
    end
  
    def create
      @property = current_user.properties.build(property_params)
  
      if @property.save
        redirect_to owner_dashboard_index_path, notice: 'Property was successfully created.'
      else
        render :new
      end
    end

    def show
        @property = Property.find(params[:id])
        @houses = @property.houses.includes(:tenant)
        @user=current_user
    end

    def destroy
        @property = Property.find(params[:id])
        @property.destroy
        redirect_to owner_dashboard_index_path, notice: 'Property was successfully deleted.'
    end
  
    private
  
    def property_params
      params.require(:property).permit(:name, :description, :image_url, :location_name, :latitude, :longitude)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owner/dashboard_helper.rb
module Owner::DashboardHelper
end

app/helpers/owner/houses_helper.rb
module Owner::HousesHelper
end

app/helpers/owner/properties_helper.rb
module Owner::PropertiesHelper
end

app/views/home/index.html.erb
<div>
  <header>
    <nav class="navbar">
      
      <%= image_tag('logo.png', alt: 'EstatePro Logo', class: 'logo') %>
      
      <!-- Navigation links on the right -->
      <div class="nav-links">
        <a href="#">Home</a>
        <a href="#">Onboard Now</a>
        <a href="<%=new_user_session_path%>">Login</a>
        <a href="#">Contact Us</a>
        <a href="#">About Us</a>
      </div>
    </nav>
  </header>

  <div class="hero-section">
    
    <h2>Welcome to EstatePro</h2>
    <p>Your one-stop solution for property owners and tenants.</p>
    <a href="#" class="cta-button">Onboard Now</a>
  </div>

  <div class="main-content">
    <section class="owners-message">
      <h2>For Property Owners</h2>
      <p>Maximize your property's potential with our professional management services. Join us and experience hassle-free property management.</p>
    </section>

    <section class="tenants-message">
      <h2>For Tenants</h2>
      <p>Find your dream home with us. Explore our available properties and enjoy a seamless renting experience.</p>
    </section>
  </div>

  <footer class="footer">
    <%= image_tag('logo.png', alt: 'EstatePro Logo', class: 'footer-logo') %>
    &copy; 2024 Estate. All rights reserved.
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homesolution</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    
  </body>
  <script src="https://kit.fontawesome.com/9b0c61e371.js" crossorigin="anonymous"></script>

</html>

app/views/owner/dashboard/index.html.erb
<div>
    <div class="top-bar">
        <div class="dashboard-logo-wrapper">
            <%= image_tag('logo.png', alt: 'backgroundImage') %>
        </div>
        <div class="search-bar">
            <div class="search-wrapper">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
            <p> Search Property,customer, etc</p>
        </div>

        <div class="user-profile-info">
          <div class="notification-bar">
            <i class="fa-regular fa-bell"></i>
          </div>
          <div class="profile-photo">
            <img src="https://neweralive.na/storage/images/2023/may/lloyd-sikeba.jpg" alt="profile photo">
          </div>
          <div class="profile-details">
             <h4><%=@user.name%></h4>
             <p><%=@user.role%></p>
          </div>
        </div>

        
    
    </div>
    <div class="dashboard-container">
        <div class="side-bar">
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?(owner_dashboard_index_path) %>">
                <i class="fa-solid fa-city"></i>
                <p>Properties</p>
            </a>
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?("/") %>">
                <i class="fa-solid fa-users"></i>
                <p>Tenants</p>
            </a>
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?("/") %>">
                <i class="fa-solid fa-money-bills"></i>
                <p>Payments</p>
            </a>
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?("/") %>">
                <i class="fa-solid fa-clipboard"></i>
                <p>Reports</p>
            </a>
            <%= button_to destroy_user_session_path, method: :delete, class: "logout-link" do %>
                <i class="fa-solid fa-sign-out"></i>
                <p>Logout</p>
            <% end %>
        </div>
        <div class ="main-section-dashboard">
            <div class="main-section-dashboard-wrapper">
                <div class="dashboard-wrapper-bar">
                    <h2>
                        My Property List
                    </h2>
                    <a href="<%=new_owner_property_path%>">+ Add Property</a>
                </div>
                <div class="main-property">
                    <div class="dashboard-filters">
                        <div class="search-bar-property">
                            <div class="search-wrapper">
                                <i class="fa-solid fa-magnifying-glass"></i>
                            </div>
                            <p> search by property name</p>
                        </div>
                        <div class="search-bar-property-two">
                            <p> fully occupied</p>
                            <div class="search-wrapper">
                                <i class="fa-solid fa-angle-down"></i>
                            </div>
                        </div>

                    </div>
                    <div class="grid-container">
                        <% puts @properties%>
                        <% @properties.each do |property| %>

                            <a href="<%= owner_property_path(property) %>" class="property-card">
                                <div class="property-photo">
                                    <img src="<%=property.image_url%>" alt="profile photo">
                                </div>
                                <div class="property-more-detail">
                                    <div class="property-name">
                                        <h3><%= property.name%></h3>
                                    </div>
                                    <div class="property-location">
                                        <span><i class="fa-solid fa-location-dot"></i></span>
                                        <p><%=property.location_name%>
                                    </div>
                                </div>
                                <div class="property-house-detail">
                                    <div class="property-house-number">
                                        <i class="fa-regular fa-building"></i>
                                        <span><%= property.houses.count %> Units</span>
                                    </div>
                                    <div class="property-house-occupied">
                                        <i class="fa-regular fa-user"></i>
                                        <span><%= property.houses.where(occupied: true).count %> Occupied</span>
                                    </div>
                                    <div class="property-house-vacant">
                                        <i class="fa-regular fa-user"></i>
                                        <span><%= property.houses.where(occupied: false).count %> Vacant</span>
                                    </div>

                                </div>
                                <div class="property-revenue">
                                    <div class="property-revenue-detail">
                                        <div class="property-rent-collected">
                                            <p> <%= number_to_currency(calculate_current_month_rent(property)) %></p>
                                        </div>
                                        <p>Amount Collected</p>
                                    </div>
                                    <div class="property-revenue-detail">
                                        <div class="property-rent-collected">
                                            <p> <%= number_to_percentage(calculate_percentage_collected(property), precision: 2) %></p>
                                        </div>
                                        <p>Percentage collection</p>
                                    </div>
                                    <div class ="property-crud-icons">
                                        <i class="fa-regular fa-pen-to-square"></i>
                                        <i class="fa-solid fa-trash"></i>
                                    </div>
                                </div>


                            </a>
                        <%end%>
                    </div>
                </div>
            </div>
        </div>
    <div>
</div>

app/views/owner/properties/_form.html.erb
<%= form_with(model: property, url: owner_properties_path, method: :post) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, 'error') %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>
  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>
  <div class="field">
    <%= form.label :location_name %>
    <%= form.text_field :location_name %>
  </div>



  <!-- Add fields as needed -->

  <div class="actions">
    <%= form.submit 'Create Property' %>
  </div>
<% end %>

app/views/owner/properties/new.html.erb
<div>
    <div class="top-bar">
        <div class="dashboard-logo-wrapper">
            <%= image_tag('logo.png', alt: 'backgroundImage') %>
        </div>
        <div class="search-bar">
            <div class="search-wrapper">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
            <p> Search Property,customer, etc</p>
        </div>

        <div class="user-profile-info">
          <div class="notification-bar">
            <i class="fa-regular fa-bell"></i>
          </div>
          <div class="profile-photo">
            <img src="https://neweralive.na/storage/images/2023/may/lloyd-sikeba.jpg" alt="profile photo">
          </div>
          <div class="profile-details">
             <h4><%=@user.name%></h4>
             <p><%=@user.role%></p>
          </div>
        </div>

        
    
    </div>
    <div class="dashboard-container">
        <div class="side-bar">
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?(owner_dashboard_index_path) %>">
                <i class="fa-solid fa-city"></i>
                <p>Properties</p>
            </a>
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?("/") %>">
                <i class="fa-solid fa-users"></i>
                <p>Tenants</p>
            </a>
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?("/") %>">
                <i class="fa-solid fa-money-bills"></i>
                <p>Payments</p>
            </a>
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?("/") %>">
                <i class="fa-solid fa-clipboard"></i>
                <p>Reports</p>
            </a>
            <%= button_to destroy_user_session_path, method: :delete, class: "logout-link" do %>
                <i class="fa-solid fa-sign-out"></i>
                <p>Logout</p>
            <% end %>
        </div>
        <div class ="main-section-dashboard">
            <div class="main-section-dashboard-wrapper">
                <div class="dashboard-wrapper-bar">
                    <h2>
                        New Property
                    </h2>
                </div>
                <div class="main-property">


                    <%= render 'form', property: @property %>
                    
                    
                </div>
            </div>
        </div>
    <div>
</div>

app/views/owner/properties/show.html.erb
<div>
    <div class="top-bar">
        <div class="dashboard-logo-wrapper">
            <%= image_tag('logo.png', alt: 'backgroundImage') %>
        </div>
        <div class="search-bar">
            <div class="search-wrapper">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
            <p> Search Property,customer, etc</p>
        </div>

        <div class="user-profile-info">
          <div class="notification-bar">
            <i class="fa-regular fa-bell"></i>
          </div>
          <div class="profile-photo">
            <img src="https://neweralive.na/storage/images/2023/may/lloyd-sikeba.jpg" alt="profile photo">
          </div>
          <div class="profile-details">
             <h4><%=@user.name%></h4>
             <p><%=@user.role%></p>
          </div>
        </div>

        
    
    </div>
    <div class="dashboard-container">
        <div class="side-bar">
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?(owner_dashboard_index_path) %>">
                <i class="fa-solid fa-city"></i>
                <p>Properties</p>
            </a>
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?("/") %>">
                <i class="fa-solid fa-users"></i>
                <p>Tenants</p>
            </a>
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?("/") %>">
                <i class="fa-solid fa-money-bills"></i>
                <p>Payments</p>
            </a>
            <a href="<%= owner_dashboard_index_path %>" class="<%= 'active' if current_page?("/") %>">
                <i class="fa-solid fa-clipboard"></i>
                <p>Reports</p>
            </a>
            <%= button_to destroy_user_session_path, method: :delete, class: "logout-link" do %>
                <i class="fa-solid fa-sign-out"></i>
                <p>Logout</p>
            <% end %>
        </div>
        <div class ="main-section-dashboard">
            <div class="main-section-dashboard-wrapper">
                <div class="dashboard-wrapper-bar">
                    <h2>
                        Property Details
                    </h2>
                    <a href="<%=new_owner_property_path%>">+ Add Property</a>
                </div>
                <div class="main-property">
                    <div class="property-details">
                        <h2>Property Details</h2>
                        <table class="property-table">
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Location</th>
                            <th>Latitude</th>
                            <th>Longitude</th>
                        </tr>
                        <tr>
                            <td><%= @property.name %></td>
                            <td><%= @property.description %></td>
                            <td><%= @property.location_name %></td>
                            <td><%= @property.latitude %></td>
                            <td><%= @property.longitude %></td>
                        </tr>
                        </table>
                    
                        <h2>Houses in <%= @property.name %></h2>
                        <table class="house-table">
                        <tr>
                            <th>House Name</th>
                            <th>Description</th>
                            <th>Tenant Name</th>
                            <th>Rent Paid</th>
                        </tr>
                        <% @houses.each do |house| %>
                            <tr>
                            <td><%= house.name %></td>
                            <td><%= house.description %></td>
                            <td><%= house.tenant&.name || 'Vacant' %></td>
                            <td><%= house.paid? ? 'Yes' : 'No' %></td>
                            </tr>
                        <% end %>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    <div>
</div>